CREATE TABLE IF NOT EXISTS students (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  first_name VARCHAR(20) NOT NULL,
  last_name VARCHAR(20) NOT NULL,
  email VARCHAR(255) NOT NULL UNIQUE CHECK (email LIKE '%@%.%'),
);

CREATE TABLE IF NOT EXISTS courses (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  course_code VARCHAR(10) NOT NULL UNIQUE CHECK (course_code LIKE '%-%'),
  title VARCHAR(20) NOT NULL,
  credit_hours INT NOT NULL,
  instructor VARCHAR(20) NOT NULL,
  total_students INT DEFAULT 0,
);

CREATE TABLE IF NOT EXISTS enrollments (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  student_id INT NOT NULL,
  course_id INT NOT NULL,
  FOREIGN KEY (course_id) REFERENCES courses(id)
  FOREIGN KEY (student_id) REFERENCES students(id)
);

CREATE TABLE IF NOT EXISTS grade_items (
  id INT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  enrollment_id INT NOT NULL,
  title VARCHAR(20) NOT NULL,
  category VARCHAR(20) NOT NULL,
  score FLOAT NOT NULL,
  max_score FLOAT DEFAULT 100.0,
  feedback TEXT DEFAULT "No feedback given.",
  weight FLOAT NOT NULL,
  FOREIGN KEY(enrollment_id) REFERENCES enrollments(id)
);
